### ISSUE TITLE
Error on 0.4: Ranges not defined

### ISSUE THREAD

**Issue by rened** [stevengj/PyPlot.jl#130]
When using a current 0.4 build and PyPlot master I get the following error. While `Ranges` is defined in 0.3 it does not exist anymore in (recent versions of?) 0.4.

```jl
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4757 (2015-05-09 17:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a01bd47* (1 day old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using PyPlot
ERROR: LoadError: LoadError: LoadError: UndefVarError: Ranges not defined
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in reload_path at ./loading.jl:158
 in _require at ./loading.jl:70
 in require at ./loading.jl:56
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in reload_path at ./loading.jl:158
 in _require at ./loading.jl:70
 in require at ./loading.jl:53
while loading /Users/rene/.julia/dev/v0.4/PyCall/src/conversions.jl, in expression starting on line 618
while loading /Users/rene/.julia/dev/v0.4/PyCall/src/PyCall.jl, in expression starting on line 153
while loading /Users/rene/.julia/dev/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 3
```

**Comment by rened** [comment]
Ok, ic, this is fixed in PyCall master. I think it might be worthwhile to tag PyCall, seems to be a crucial fix. Thanks!

**Comment by stevengj** [comment]
In general, if you are using Julia 0.4, you will often find yourself needing master versions of many packages...

**Comment by glwhart** [comment]
I have the same problem (we need python 0.4 for nullable parametric types). Glad to see the fix...but I'm not sure how to apply it. Can you tell me?

**Comment by rened** [comment]
@glwhart You can use the master branch of `PyPlot` (instead of the newest tagged version) by running `Pkg.checkout("PyPlot")`. To get back to the tagged version run `Pkg.free("PyPlot")`

**Comment by glwhart** [comment]
Sorry, I'm still a beginner at both julia and github. This still doesn't do the trick. It seems it's not really checking out the latest pyplot. (See below.)

I also tried `Pkg.rm("PyPlot")` and then `Pkg.checkout("PyPlot")` but I still have the ranges not defined problem.

```julia
julia> Pkg.checkout("PyPlot")
INFO: Checking out PyPlot master...
INFO: Pulling PyPlot latest master...
INFO: No packages to install, update or remove

julia> using PyPlot
ERROR: LoadError: LoadError: LoadError: UndefVarError: Ranges not defined
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in reload_path at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in reload_path at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
while loading /Users/hart/.julia/v0.4/PyCall/src/conversions.jl, in expression starting on line 618
while loading /Users/hart/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 153
while loading /Users/hart/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 3```

**Comment by stevengj** [comment]
@glwhart, you should also `Pkg.checkout("PyCall")`.

If you are a beginner at Julia, you should strongly consider using the stable version (0.3).

**Comment by rened** [comment]
@glwhart sorry, my bad, you need `Pkg.checkout("PyCall")`

**Comment by glwhart** [comment]
@stevengj  I need Nullable for a parametric type. Couldn't figure out how to do something equivalent for version 0.3. Perhaps I was wrong but...Here's an example:
```julia
type OrientedDart{T, S}
    index::T
    # involutions or references to other darts in the GeneralizedMap
    phi::Vector{Nullable{OrientedDart{T,S}}}
    # data associated with a global set of darts (an orbit or k-cell)
    globalembed::Vector{Nullable{S}}
    # references to the dart where the data is stored for each dim
    embedloc::Vector{Nullable{OrientedDart{T,S}}}
    isboundary::Bool
end
```
@rened Thanks, I just figured a few minutes ago that it was PyCall that was causing the problem. Also, Pkg.status() was really helpful. Just learned that too. Plotting now works in IJulia, but not in the REPL (something about "pltm not defined").

**Comment by rened** [comment]
@glwhart you can use `Compat.jl` for a `Nullable` for 0.3
