### ISSUE TITLE
A warning requiring gtk version

### ISSUE THREAD

**Issue by zhujinxuan** [stevengj/PyPlot.jl#181]
When I run `using PyPlot`, it gives a warning about gtk version...
```
using PyPlot
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
```

How shall I config my python or julia to remove the warning?  

Thank you.

**Comment by stevengj** [comment]
Hmm, is this something new?  Possibly PyCall's [gtk routine](https://github.com/stevengj/PyCall.jl/blob/master/src/gui.jl#L80-L91) needs to be updated to call `gi.require_version` for the `gi` module.

**Comment by zhujinxuan** [comment]
I guess it is something new....  I forgot whether I have met the warning last month, but I remembered that the error did not happen in September.

**Comment by zhujinxuan** [comment]
I guess it is something new, it did not happen at September.

**Comment by stevengj** [comment]
Looks like it was [added in January 2015](https://git.gnome.org/browse/pygobject/commit/gi/importer.py?id=ef3bff4e570363e4f383d4cdae9cecd4073b03d8) to Gtk, and must be appearing in OS packages only now.

**Comment by stevengj** [comment]
Should be fixed now with stevengj/PyCall.jl@70232dabb57e5cd97efc1856d940a8eec3f8dfec.  @zhujinxuan, can you try fetching the latest version of PyCall via:
```jl
Pkg.checkout("PyCall")
Pkg.build("PyCall")
```
and confirm that it silences the warning

**Comment by zhujinxuan** [comment]
Still there is a warning...
I guess whether there is any python package I need to install about it...

**Comment by stevengj** [comment]
Grr, maybe I need to add the `require_version` in PyPlot.

**Comment by stefabat** [comment]
Problem is still there. I think is in PyPlot, because importing matplotlib using `@pyimport matplotlib` does not give any warning..

**Comment by stevengj** [comment]
@stefabat, `@pyimport matplotlib` may be using a different (non-GTK) backend.

**Comment by zsoerenm** [comment]
I also get this error. Here is the full output:
```
using PyPlot
INFO: Recompiling stale cache file /home/zorn/.julia/lib/v0.4/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/zorn/.julia/lib/v0.4/PyPlot.ji for module PyPlot.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
/usr/lib/python3.5/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
WARNING: No working GUI backend found for matplotlib.
ERROR: InitError: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError('Cairo backend requires that cairocffi or pycairo is installed.',)
  File "/usr/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3agg.py", line 12, in <module>
    from .backend_cairo import cairo, HAS_CAIRO_CFFI
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_cairo.py", line 38, in <module>
    raise ImportError("Cairo backend requires that cairocffi or pycairo is installed.")

 [inlined code] from /home/zorn/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/zorn/.julia/v0.4/PyCall/src/PyCall.jl:308
 in __init__ at /home/zorn/.julia/v0.4/PyPlot/src/PyPlot.jl:250
 in _require_from_serialized at loading.jl:84
during initialization of module PyPlot
```

**Comment by stevengj** [comment]
@zsoerenm, that's an unrelated issue; as the error message indicates, probably you need to install `pycairo`.

**Comment by stevengj** [comment]
@juliohm and others, does `Pkg.checkout("PyCall")` (to get https://github.com/stevengj/PyCall.jl/commit/71495c17b1a483336587bf978edc94e5a6ea0d06) eliminate the warning?

**Comment by juliohm** [comment]
@stevengj yes, the warning regarding Gtk is gone, thanks. I still get a warning regarding Cairo, but I think this is an issue regarding my setup here, correct?

>/usr/lib/python3.5/site-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "

**Comment by stevengj** [comment]
Good to hear that this will be fixed by the next tagged version (1.6.1 should be tagged soon).    The Cairo warning seems like it is an issue with your Python setup.
